import Header from "@/components/Header"
import "./globals.css"
import { Manrope } from "next/font/google"
import Footer from "@/components/Footer"

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
})

export const metadata = {
  title: "Expedia",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
